import { FormValues } from "@/components/subscribers/FormBuilder";

export const formTemplates: Record<string, FormValues> = {
  basic: {
    name: "Basic Newsletter Signup",
    description: "A simple email-only signup form for your newsletter",
    fields: [
      {
        id: "email-field",
        type: "email",
        label: "Email Address",
        placeholder: "your@email.com",
        required: true,
      },
    ],
    settings: {
      submitButtonText: "Subscribe",
      successMessage: "Thank you for subscribing to our newsletter!",
      doubleOptIn: false,
      redirectUrl: "",
      honeypotEnabled: true,
      recaptchaEnabled: false,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#3b82f6",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      fontFamily: "Inter, sans-serif",
      borderRadius: "4",
      buttonStyle: "filled",
    },
  },

  detailed: {
    name: "Detailed Subscriber Form",
    description: "Collect more information about your subscribers",
    fields: [
      {
        id: "first-name",
        type: "text",
        label: "First Name",
        placeholder: "John",
        required: true,
      },
      {
        id: "last-name",
        type: "text",
        label: "Last Name",
        placeholder: "Doe",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "john@example.com",
        required: true,
      },
      {
        id: "company",
        type: "text",
        label: "Company",
        placeholder: "Acme Inc.",
        required: false,
      },
    ],
    settings: {
      submitButtonText: "Sign Up",
      successMessage: "Thank you for subscribing! We've sent you a confirmation email.",
      doubleOptIn: true,
      redirectUrl: "",
      honeypotEnabled: true,
      recaptchaEnabled: true,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#4f46e5",
      backgroundColor: "#ffffff",
      textColor: "#1f2937",
      fontFamily: "Roboto, sans-serif",
      borderRadius: "8",
      buttonStyle: "filled",
    },
  },

  leadMagnet: {
    name: "Lead Magnet Opt-in",
    description: "Collect leads with a free resource offer",
    fields: [
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "your@email.com",
        required: true,
      },
      {
        id: "consent",
        type: "checkbox",
        label: "I agree to receive marketing emails and can unsubscribe at any time",
        required: true,
      },
    ],
    settings: {
      submitButtonText: "Get Free Download",
      successMessage: "Your download is on its way to your inbox!",
      doubleOptIn: false,
      redirectUrl: "/thank-you",
      honeypotEnabled: true,
      recaptchaEnabled: false,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#16a34a",
      backgroundColor: "#f0fdf4",
      textColor: "#166534",
      fontFamily: "Poppins, sans-serif",
      borderRadius: "12",
      buttonStyle: "filled",
    },
  },

  event: {
    name: "Event Registration",
    description: "Register attendees for your upcoming event",
    fields: [
      {
        id: "full-name",
        type: "text",
        label: "Full Name",
        placeholder: "John Doe",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "john@example.com",
        required: true,
      },
      {
        id: "job-title",
        type: "text",
        label: "Job Title",
        placeholder: "Marketing Manager",
        required: false,
      },
      {
        id: "session",
        type: "select",
        label: "Which session would you like to attend?",
        required: true,
        options: ["Morning Session", "Afternoon Session", "Both Sessions"],
      },
      {
        id: "dietary",
        type: "select",
        label: "Dietary Requirements",
        required: false,
        options: ["None", "Vegetarian", "Vegan", "Gluten-Free", "Other"],
      },
    ],
    settings: {
      submitButtonText: "Register Now",
      successMessage: "You're registered! Check your email for confirmation details.",
      doubleOptIn: false,
      redirectUrl: "",
      honeypotEnabled: true,
      recaptchaEnabled: true,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#d946ef",
      backgroundColor: "#faf5ff",
      textColor: "#6b21a8",
      fontFamily: "Montserrat, sans-serif",
      borderRadius: "8",
      buttonStyle: "filled",
    },
  },

  minimal: {
    name: "Minimal Signup",
    description: "A clean, minimal signup form with just an email field",
    fields: [
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email address",
        required: true,
      },
    ],
    settings: {
      submitButtonText: "Subscribe",
      successMessage: "Thanks for subscribing!",
      doubleOptIn: false,
      redirectUrl: "",
      honeypotEnabled: true,
      recaptchaEnabled: false,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#111827",
      backgroundColor: "#ffffff",
      textColor: "#111827",
      fontFamily: "system-ui, sans-serif",
      borderRadius: "0",
      buttonStyle: "outline",
    },
  },

  survey: {
    name: "Newsletter Preferences",
    description: "Learn about your subscribers' interests",
    fields: [
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "your@email.com",
        required: true,
      },
      {
        id: "first-name",
        type: "text",
        label: "First Name",
        placeholder: "John",
        required: false,
      },
      {
        id: "interests",
        type: "select",
        label: "What topics are you most interested in?",
        required: true,
        options: [
          "Industry News",
          "Product Updates",
          "Tips & Tutorials",
          "Case Studies",
          "All of the above",
        ],
      },
      {
        id: "frequency",
        type: "select",
        label: "How often would you like to hear from us?",
        required: true,
        options: ["Daily", "Weekly", "Bi-weekly", "Monthly"],
      },
    ],
    settings: {
      submitButtonText: "Save Preferences",
      successMessage: "Your preferences have been saved. Thanks for customizing your experience!",
      doubleOptIn: false,
      redirectUrl: "",
      honeypotEnabled: true,
      recaptchaEnabled: false,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#f59e0b",
      backgroundColor: "#fffbeb",
      textColor: "#92400e",
      fontFamily: "Inter, sans-serif",
      borderRadius: "8",
      buttonStyle: "filled",
    },
  },

  contact: {
    name: "Contact Form",
    description: "A simple contact form to collect inquiries",
    fields: [
      {
        id: "name",
        type: "text",
        label: "Name",
        placeholder: "Your name",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "your@email.com",
        required: true,
      },
      {
        id: "subject",
        type: "select",
        label: "Subject",
        required: true,
        options: ["General Inquiry", "Support", "Partnership", "Other"],
      },
      {
        id: "message",
        type: "text",
        label: "Message",
        placeholder: "Your message here...",
        required: true,
      },
      {
        id: "newsletter",
        type: "checkbox",
        label: "Subscribe to our newsletter",
        required: false,
      },
    ],
    settings: {
      submitButtonText: "Send Message",
      successMessage: "Your message has been sent! We'll get back to you soon.",
      doubleOptIn: false,
      redirectUrl: "",
      honeypotEnabled: true,
      recaptchaEnabled: true,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#0ea5e9",
      backgroundColor: "#f0f9ff",
      textColor: "#0c4a6e",
      fontFamily: "Roboto, sans-serif",
      borderRadius: "4",
      buttonStyle: "filled",
    },
  },

  dark: {
    name: "Dark Mode Form",
    description: "A sleek dark-themed subscription form",
    fields: [
      {
        id: "email",
        type: "email",
        label: "Email Address",
        placeholder: "your@email.com",
        required: true,
      },
      {
        id: "name",
        type: "text",
        label: "Your Name",
        placeholder: "John Doe",
        required: false,
      },
    ],
    settings: {
      submitButtonText: "Join the Waitlist",
      successMessage: "You're on the list! We'll keep you updated.",
      doubleOptIn: true,
      redirectUrl: "",
      honeypotEnabled: true,
      recaptchaEnabled: false,
      recaptchaSiteKey: "",
    },
    style: {
      primaryColor: "#a78bfa",
      backgroundColor: "#1e1b4b",
      textColor: "#e0e7ff",
      fontFamily: "Inter, sans-serif",
      borderRadius: "8",
      buttonStyle: "outline",
    },
  },
};
